Repository pivotal-cf/terraforming-gcp, pull requests merged in 2018-10, with the labels that each got.

#97 Add ops_manager_private_ip
  outputs.tf
Labels: in progress

#99 Enable private ip google access when internetless
  networks.tf
Labels: unscheduled

#91 Add missing required API
  README.md
Labels: scheduled

#90 Iso Seg module now respects 'internetless' flag
  README.md
  isolation_segment/dns.tf
  isolation_segment/outputs.tf
  isolation_segment/variables.tf
  modules.tf
  outputs.tf
Labels: in progress

#88 extracted ops manager into its own module
  dns.tf
  modules.tf
  ops_manager.tf
  ops_manager/bucket.tf
  ops_manager/dns.tf
  ops_manager/eip.tf
  ops_manager/firewall.tf
  ops_manager/image.tf
  ops_manager/instance.tf
  ops_manager/keypair.tf
  ops_manager/optional_instance.tf
  ops_manager/outputs.tf
  ops_manager/variables.tf
  outputs.tf
Labels: in progress
